logging:
  level: "DEBUG"

server:
  port: 8080
  read-timeout: 10s
  write-timeout: 10s
  idle-timeout: 15s
  max-header-bytes: 1048576 # 1MB

routes:
  "/api/v1/users":
    - url: "http://localhost:5001"
      health:
        path: "/ping"
        timeout: 1s
      weight: 2
    - url: "http://localhost:5002"
      health:
        path: "/ping"
        timeout: 1s
      weight: 1
  "/api/v1/products":
    - url: "http://localhost:7001"
      health:
        path: "/ping"
        timeout: 1s
      weight: 4
    - url: "http://localhost:7002"
      health:
        path: "/ping"
        timeout: 1s
      weight: 2
    - url: "http://localhost:7003"
      health:
        path: "/ping"
        timeout: 1s
      weight: 1
    - url: "http://localhost:7004"
      health:
        path: "/ping"
        timeout: 1s
      weight: 1
  "/api/v1/orders":
    - url: "http://localhost:6001"
      health:
        path: "/ping"
        timeout: 1s
      weight: 1
    - url: "http://localhost:6002"
      health:
        path: "/ping"
        timeout: 1s
      weight: 1

loadbalancer:
  strategy: "round_robin"
