logging:
  level: "DEBUG"

routes:
  "/api/v1/users":
    - url: "http://localhost:5001"
      health-path: "/ping"
      weight: 2
    - url: "http://localhost:5002"
      health-path: "/ping"
      weight: 1
  "/api/v1/products":
    - url: "http://localhost:7001"
      health-path: "/ping"
      weight: 4
    - url: "http://localhost:7002"
      health-path: "/ping"
      weight: 2
    - url: "http://localhost:7003"
      health-path: "/ping"
      weight: 1
    - url: "http://localhost:7004"
      health-path: "/ping"
      weight: 1
  "/api/v1/orders":
    - url: "http://localhost:6001"
      health-path: "/ping"
      weight: 1
    - url: "http://localhost:6002"
      health-path: "/ping"
      weight: 1

loadbalancer:
  strategy: "round_robin"
